### ISSUE TITLE
Final cursor position is wrong

### ISSUE THREAD

**Issue by streamtree** [onolox/SmartSemicolon#1]
It would be more useful (and intuitive) if these changes were made:

1. If the semicolon is typed at the end of the line then the extension should do nothing (currently it moves the cursor to the left of the semicolon and changes the backspace behavior).

2. If the semicolon is typed in the middle of a line that already has a semicolon at the end, the extension should also do nothing (it currently behaves correctly in this scenario).

3. If the semicolon is typed in the middle of a line that does not have a semicolon at the end, the semicolon should be placed at the end of the line and the cursor should still end up to the right of the semicolon. Backspace should return the cursor to the original position. 

4. Typing a double semicolon (';;') in the middle of a line that does not have a semicolon at the end should place a semicolon at the current cursor position and move the cursor to the right of it. (No semicolon should be at the end of the line when done.) Backspace should delete the semicolon.

**Comment by onolox** [comment]
I will corret the number one.

At first I used the behavior of Eclipse, but for me is better to maintain the cursor.
