### ISSUE TITLE
Not Adding Semicolon

### ISSUE THREAD

**Issue by Adhil-Suresh** [onolox/SmartSemicolon#8]
i am using visual studio 2017 and installed smart semicolon extension but it has not been adding semicolon
![ice_screenshot_20190502-124321](https://user-images.githubusercontent.com/43722374/57060736-173b2a80-6cd8-11e9-88ad-f80522338ce9.png)
![ice_video_20190502124419](https://user-images.githubusercontent.com/43722374/57060797-4b165000-6cd8-11e9-8ca9-53e351dcc15e.gif)

**Comment by onolox** [comment]
I have cleaned the project, plz try again.
